# _config.yml
title: 我的日记本
description: 记录生活的点点滴滴
author: YolandaYingzi

# 移除 baseurl，只保留 url
url: "https://yolanda-yingzi.github.io"

theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# 定义文章的永久链接格式
permalink: /posts/:title/

paginate: 10
paginate_path: "/page:num/"
